version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: homefinance-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=homefinancedb
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  homefinance:
    build: .
    container_name: homefinance
    depends_on:
      - db
    ports:
      - "8585:8585"
      - "5005:5005"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/homefinancedb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_PROFILES_ACTIVE=dev

volumes:
  mysql-data:
