spring.application.name=homefinance
spring.data.mongodb.database=finance-api-db
spring.data.mongodb.uri=mongodb+srv://asankanz:nLGPApJ5QLMKLTji@cluster0.kqfad.mongodb.net/
server.port=8585

# MySQL Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/homefinance-mysql?useSSL=false&serverTimezone=UTC
spring.datasource.username=admin
spring.datasource.password=password

# Hibernate JPA Properties
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
